version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  graphql:
    build:
      context: ./backend
    container_name: showcase-graphql
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://your_username:your_password@postgres:5432/your_database
    depends_on:
      - postgres

volumes:
  pgdata:
